import type { LocalizedText, PortfolioCategory, PortfolioProject } from "@/types";

export const portfolioCategories: { key: PortfolioCategory; label: LocalizedText }[] = [
  {
    key: "ecommerce",
    label: {
      en: "E-commerce",
      fr: "E-commerce",
      ar: "تجارة إلكترونية",
    },
  },
  {
    key: "business",
    label: {
      en: "Business",
      fr: "Entreprise",
      ar: "أعمال",
    },
  },
  {
    key: "booking",
    label: {
      en: "Booking",
      fr: "Réservation",
      ar: "حجز",
    },
  },
  {
    key: "landing",
    label: {
      en: "Landing Page",
      fr: "Landing Page",
      ar: "صفحة هبوط",
    },
  },
  {
    key: "portfolio",
    label: {
      en: "Portfolio",
      fr: "Portfolio",
      ar: "بورتفوليو",
    },
  },
  {
    key: "medical",
    label: {
      en: "Medical",
      fr: "Médical",
      ar: "طبي",
    },
  },
  {
    key: "travel",
    label: {
      en: "Travel",
      fr: "Voyage",
      ar: "سفر",
    },
  },
  {
    key: "education",
    label: {
      en: "Education",
      fr: "Éducation",
      ar: "تعليم",
    },
  },
  {
    key: "community",
    label: {
      en: "Community",
      fr: "Communauté",
      ar: "مجتمع",
    },
  },
  {
    key: "blog",
    label: {
      en: "Blog",
      fr: "Blog",
      ar: "مدونة",
    },
  },
];

/**
 * Ordered exactly as requested for the /portfolio page (do not sort
 * alphabetically or resort by category). To add a new project later,
 * append an entry here and drop its screenshot into public/images/portfolio.
 */
export const portfolioProjects: PortfolioProject[] = [
  {
    id: "1913",
    title: "Nakama Store",
    slug: "nakama-store",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-06-19-at-00.23.44-scaled.png",
    url: "https://nakamastore.ma/",
  },
  {
    id: "1909",
    title: "Mawlo",
    slug: "mawlo",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-06-04-at-22.15.34-scaled.png",
    url: "https://mawlo.co/",
  },
  {
    id: "1796",
    title: "Cutt Salons",
    slug: "cutt-salons",
    categories: ["booking"],
    description: {
      en: "A booking-friendly website that makes it easy for clients to reserve services online.",
      fr: "Un site orienté réservation qui facilite la prise de rendez-vous en ligne pour les clients.",
      ar: "موقع سهل الحجز يتيح للعملاء حجز الخدمات عبر الإنترنت بكل يسر.",
    },
    image: "/images/portfolio/Screenshot-2026-03-25-at-23.59.48-scaled.png",
    url: "https://cuttsalons.com/",
  },
  {
    id: "1793",
    title: "Light Way Pro",
    slug: "light-way-pro",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2026-03-26-at-00.00.15-scaled.png",
    url: null,
  },
  {
    id: "1900",
    title: "Mille & Un Fil",
    slug: "mille-un-fil",
    categories: ["business", "landing"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2026-04-27-at-20.55.22-scaled.png",
    url: "https://1001fil.com/",
  },
  {
    id: "1788",
    title: "5 w Khmis",
    slug: "5-w-khmis",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-03-26-at-00.01.32-scaled.png",
    url: "https://5wkhmis.com/",
  },
  {
    id: "1774",
    title: "Star Tech",
    slug: "star-tech",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-01-31-at-12.46.35-scaled.png",
    url: "https://perseetech.com/",
  },
  {
    id: "1757",
    title: "O’TAS Fencing & Gates",
    slug: "otas-fencing-gates",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2026-01-08-at-23.24.22-scaled.png",
    url: "https://otasfencing.com/",
  },
  {
    id: "1691",
    title: "Ayssoun",
    slug: "ayssoun",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-12-21-at-15.40.24-scaled.png",
    url: "https://ayssoun.com/",
  },
  {
    id: "1688",
    title: "Myriam Parfumerie",
    slug: "myriam-parfumerie",
    categories: ["booking"],
    description: {
      en: "A booking-friendly website that makes it easy for clients to reserve services online.",
      fr: "Un site orienté réservation qui facilite la prise de rendez-vous en ligne pour les clients.",
      ar: "موقع سهل الحجز يتيح للعملاء حجز الخدمات عبر الإنترنت بكل يسر.",
    },
    image: "/images/portfolio/Screenshot-2025-12-21-at-15.36.55-scaled.png",
    url: "https://myriamparfumerie.ma/",
  },
  {
    id: "1778",
    title: "Auralux Parfums",
    slug: "star-tech-2",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-02-10-at-14.46.59-scaled.png",
    url: "https://auraluxparfums.com/",
  },
  {
    id: "1684",
    title: "100 Dryal",
    slug: "100-dryal",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-11-29-at-23.54.56-scaled.png",
    url: "https://100dryal.com/",
  },
  {
    id: "1675",
    title: "Moroccan Travel Guide",
    slug: "moroccan-travel-guide",
    categories: ["travel"],
    description: {
      en: "A travel and tourism website designed to showcase destinations and convert visitors into bookings.",
      fr: "Un site de voyage et de tourisme conçu pour mettre en valeur les destinations et convertir les visiteurs en réservations.",
      ar: "موقع للسفر والسياحة صُمم لعرض الوجهات وتحويل الزوار إلى حجوزات.",
    },
    image: "/images/portfolio/Screenshot-2025-11-25-at-23.58.26-scaled.png",
    url: "https://moroccantravelguide.com/",
  },
  {
    id: "1668",
    title: "Magic Lavage",
    slug: "magic-lavage",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2025-11-25-at-19.32.41-scaled.png",
    url: "https://magiclav.ma/",
  },
  {
    id: "1785",
    title: "Fresco",
    slug: "fresco",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2026-02-10-at-14.48.22-scaled.png",
    url: "https://fresco.ma/",
  },
  {
    id: "1627",
    title: "Green Home Sytems",
    slug: "green-home-sytems",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2025-10-19-at-12.47.10-scaled.png",
    url: "https://greenhome-systems.com/",
  },
  {
    id: "1613",
    title: "M Cleaning Company LLC",
    slug: "m-cleaning-company-llc",
    categories: ["booking"],
    description: {
      en: "A booking-friendly website that makes it easy for clients to reserve services online.",
      fr: "Un site orienté réservation qui facilite la prise de rendez-vous en ligne pour les clients.",
      ar: "موقع سهل الحجز يتيح للعملاء حجز الخدمات عبر الإنترنت بكل يسر.",
    },
    image: "/images/portfolio/Screenshot-2025-09-26-at-13.03.13-scaled.png",
    url: "https://mcleaningcompanyllc.com/",
  },
  {
    id: "160",
    title: "Tech Ventures",
    slug: "photo-retouching-4",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2025-08-27-at-22.44.36-scaled.png",
    url: "https://techs-spectacular-site-da0a9c.webflow.io/",
  },
  {
    id: "157",
    title: "Moro Shoes",
    slug: "photo-retouching-3",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-27-at-23.14.39-scaled.png",
    url: "https://moro-shoes.shop/",
  },
  {
    id: "154",
    title: "Siblo",
    slug: "photo-retouching-2",
    categories: ["community"],
    description: {
      en: "A community-focused website designed to connect members and share updates clearly.",
      fr: "Un site web communautaire conçu pour connecter les membres et partager les actualités clairement.",
      ar: "موقع مخصص لمجتمع معين صُمم لربط الأعضاء ومشاركة المستجدات بوضوح.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.14.02-scaled.png",
    url: "https://siblopro.com/",
  },
  {
    id: "151",
    title: "Sahara Tours Morocco",
    slug: "photo-retouching",
    categories: ["travel"],
    description: {
      en: "A travel and tourism website designed to showcase destinations and convert visitors into bookings.",
      fr: "Un site de voyage et de tourisme conçu pour mettre en valeur les destinations et convertir les visiteurs en réservations.",
      ar: "موقع للسفر والسياحة صُمم لعرض الوجهات وتحويل الزوار إلى حجوزات.",
    },
    image: "/images/portfolio/Screenshot-2025-08-27-at-23.17.16.png",
    url: "https://saharatoursmorocco.com/",
  },
  {
    id: "1254",
    title: "Summer Forever",
    slug: "summer-forever",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.01.11-scaled.png",
    url: "https://summerforever.us/",
  },
  {
    id: "1245",
    title: "Boualioui Academy",
    slug: "boualioui-academy",
    categories: ["education"],
    description: {
      en: "An educational platform designed to present courses clearly and attract new students.",
      fr: "Une plateforme éducative conçue pour présenter les formations clairement et attirer de nouveaux étudiants.",
      ar: "منصة تعليمية صُممت لعرض الدورات بوضوح وجذب طلاب جدد.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.30.02-scaled.png",
    url: "https://boualioui.academy/",
  },
  {
    id: "1241",
    title: "Nozabrand",
    slug: "nozabrand",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.17.26-scaled.png",
    url: "https://nozabrand.com/",
  },
  {
    id: "1243",
    title: "Après",
    slug: "apes",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.20.51-scaled.png",
    url: null,
  },
  {
    id: "1260",
    title: "Yns web",
    slug: "yns-web",
    categories: ["portfolio"],
    description: {
      en: "A clean, professional portfolio website that showcases work and builds credibility.",
      fr: "Un site portfolio clair et professionnel qui met en valeur le travail et renforce la crédibilité.",
      ar: "موقع بورتفوليو أنيق واحترافي يعرض الأعمال ويعزز المصداقية.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.11.45-scaled.png",
    url: "https://unrivaled-youtiao-5873f3.netlify.app/",
  },
  {
    id: "1271",
    title: "Web design",
    slug: "kay-33",
    categories: ["portfolio"],
    description: {
      en: "A clean, professional portfolio website that showcases work and builds credibility.",
      fr: "Un site portfolio clair et professionnel qui met en valeur le travail et renforce la crédibilité.",
      ar: "موقع بورتفوليو أنيق واحترافي يعرض الأعمال ويعزز المصداقية.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.55.09-scaled.png",
    url: "https://master--luminous-dasik-c462ea.netlify.app/",
  },
  {
    id: "1267",
    title: "Pommade",
    slug: "pommade",
    categories: ["medical"],
    description: {
      en: "A professional website for a medical or wellness business, built to build trust and simplify appointments.",
      fr: "Un site web professionnel pour une activité médicale ou de bien-être, conçu pour inspirer confiance et simplifier les rendez-vous.",
      ar: "موقع احترافي لنشاط طبي أو للعناية بالصحة، صُمم لبناء الثقة وتسهيل حجز المواعيد.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.13.03-scaled.png",
    url: "https://tubular-sfogliatella-9e68f6.netlify.app/",
  },
  {
    id: "1262",
    title: "Stylewox",
    slug: "stylewox",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-21.17.39-scaled.png",
    url: null,
  },
  {
    id: "1258",
    title: "Noure Lhayat",
    slug: "noure-lhayat",
    categories: ["medical"],
    description: {
      en: "A professional website for a medical or wellness business, built to build trust and simplify appointments.",
      fr: "Un site web professionnel pour une activité médicale ou de bien-être, conçu pour inspirer confiance et simplifier les rendez-vous.",
      ar: "موقع احترافي لنشاط طبي أو للعناية بالصحة، صُمم لبناء الثقة وتسهيل حجز المواعيد.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.07.35-scaled.png",
    url: null,
  },
  {
    id: "1250",
    title: "Njoyit Cosmetics",
    slug: "njoyit-cosmetics",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.21.48-scaled.png",
    url: "https://njoyitcosmetics.com/",
  },
  {
    id: "1904",
    title: "AMA Aménagement",
    slug: "ama-amenagement",
    categories: ["business", "landing"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2026-05-06-at-23.06.41-scaled.png",
    url: "https://ama-textile.com/",
  },
  {
    id: "1277",
    title: "Mr Rapers",
    slug: "mr-rapers",
    categories: ["blog"],
    description: {
      en: "A content-focused website designed to publish articles and build an engaged audience.",
      fr: "Un site orienté contenu conçu pour publier des articles et fidéliser une audience engagée.",
      ar: "موقع مخصص للمحتوى صُمم لنشر المقالات وبناء جمهور متفاعل.",
    },
    image: "/images/portfolio/shutterstock_1718636101-1-scaled-1.jpg",
    url: null,
  },
  {
    id: "1252",
    title: "Incanti.co",
    slug: "incanti-co",
    categories: ["business"],
    description: {
      en: "A professional business website designed to build credibility and attract more clients.",
      fr: "Un site web professionnel conçu pour renforcer la crédibilité et attirer davantage de clients.",
      ar: "موقع احترافي للأعمال صُمم لتعزيز المصداقية وجذب المزيد من العملاء.",
    },
    image: "/images/portfolio/Screenshot-2025-08-27-at-23.59.22-scaled.png",
    url: "https://incanti.co/",
  },
  {
    id: "1265",
    title: "Salon Mouna",
    slug: "salon-mouna",
    categories: ["booking"],
    description: {
      en: "A booking-friendly website that makes it easy for clients to reserve services online.",
      fr: "Un site orienté réservation qui facilite la prise de rendez-vous en ligne pour les clients.",
      ar: "موقع سهل الحجز يتيح للعملاء حجز الخدمات عبر الإنترنت بكل يسر.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.05.47-scaled.png",
    url: null,
  },
  {
    id: "1256",
    title: "Muse Club",
    slug: "muse-club",
    categories: ["booking"],
    description: {
      en: "A booking-friendly website that makes it easy for clients to reserve services online.",
      fr: "Un site orienté réservation qui facilite la prise de rendez-vous en ligne pour les clients.",
      ar: "موقع سهل الحجز يتيح للعملاء حجز الخدمات عبر الإنترنت بكل يسر.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.08.05-scaled.png",
    url: null,
  },
  {
    id: "1281",
    title: "3chab",
    slug: "3chab",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/scale_1200-2.jpg",
    url: "http://3chab.ma/",
  },
  {
    id: "1274",
    title: "Charms Beauty",
    slug: "charms-beauty",
    categories: ["ecommerce"],
    description: {
      en: "A modern online store built to showcase products and turn visitors into buyers.",
      fr: "Une boutique en ligne moderne conçue pour mettre en valeur les produits et convertir les visiteurs en acheteurs.",
      ar: "متجر إلكتروني عصري صُمم لعرض المنتجات وتحويل الزوار إلى مشترين.",
    },
    image: "/images/portfolio/2e46f6132518145.61aa5bc46cc87.jpg",
    url: "http://charmsbeauty.ca",
  },
  {
    id: "1269",
    title: "Touch Screen",
    slug: "touch-screen",
    categories: ["landing"],
    description: {
      en: "A high-converting landing page built specifically to turn ad traffic into leads.",
      fr: "Une landing page à fort taux de conversion conçue pour transformer le trafic publicitaire en prospects.",
      ar: "صفحة هبوط عالية التحويل صُممت خصيصًا لتحويل زوار الإعلانات إلى عملاء محتملين.",
    },
    image: "/images/portfolio/Screenshot-2025-08-28-at-00.29.03-scaled.png",
    url: null,
  },
];

/**
 * Explicit, ordered pick of 6 projects shown in the homepage and contact
 * page portfolio previews (independent of the full list order above).
 */
export const featuredProjectIds: string[] = [
  "1913",
  "1909",
  "1796",
  "1757",
  "1254",
  "151",
];
