import type { PricingComparisonRow, PricingPackage } from "@/types";

export const pricingPackages: PricingPackage[] = [
  {
    id: "professional-wordpress",
    engine: "wordpress",
    name: {
      en: "Professional WordPress Website",
      fr: "Site Web Professionnel WordPress",
      ar: "موقع احترافي بووردبريس",
    },
    purpose: {
      en: "For businesses that need a professional, modern, responsive, easy-to-manage website at a clear starting price.",
      fr: "Pour les entreprises qui ont besoin d'un site web professionnel, moderne, responsive et facile à gérer, à un prix de départ clair.",
      ar: "للشركات التي تحتاج إلى موقع احترافي وعصري ومتجاوب وسهل الإدارة بسعر ابتدائي واضح.",
    },
    price: 2500,
    currency: "MAD",
    popular: false,
    features: {
      en: [
        "Website built with WordPress",
        "Hosting + domain name included for 1 year",
        "Professional email included",
        "Modern responsive design",
        "Mobile, tablet, and desktop optimization",
        "Contact form or booking option",
        "Pages, services, products, or blog management",
        "3 to 5 products or services added",
        "Basic Google optimization",
        "Essential security setup",
        "Tutorial videos included",
        "Easy content management after delivery",
      ],
      fr: [
        "Site web réalisé avec WordPress",
        "Hébergement + nom de domaine inclus pendant 1 an",
        "Email professionnel inclus",
        "Design moderne et responsive",
        "Optimisation mobile, tablette et ordinateur",
        "Formulaire de contact ou option de réservation",
        "Gestion des pages, services, produits ou blog",
        "3 à 5 produits ou services ajoutés",
        "Optimisation Google de base",
        "Configuration de sécurité essentielle",
        "Vidéos tutorielles incluses",
        "Gestion de contenu facile après la livraison",
      ],
      ar: [
        "موقع مبني بووردبريس",
        "استضافة + اسم نطاق لمدة سنة كاملة",
        "بريد إلكتروني احترافي مشمول",
        "تصميم عصري ومتجاوب",
        "تحسين للهاتف واللوحي والحاسوب",
        "نموذج تواصل أو خيار حجز",
        "إدارة الصفحات والخدمات والمنتجات أو المدونة",
        "إضافة 3 إلى 5 منتجات أو خدمات",
        "تحسين أساسي لمحركات البحث Google",
        "إعدادات أمان أساسية",
        "فيديوهات تعليمية مشمولة",
        "إدارة سهلة للمحتوى بعد التسليم",
      ],
    },
  },
  {
    id: "premium-custom",
    engine: "custom",
    name: {
      en: "Premium Custom Coded Website",
      fr: "Site Web Premium Sur-Mesure",
      ar: "موقع Premium مبرمج حسب الطلب",
    },
    purpose: {
      en: "For brands and businesses that want a unique, faster, more immersive, more scalable, and more advanced online experience.",
      fr: "Pour les marques et entreprises qui souhaitent une expérience en ligne unique, plus rapide, plus immersive, plus évolutive et plus avancée.",
      ar: "للعلامات التجارية والشركات التي ترغب في تجربة رقمية فريدة وأسرع وأكثر غامرة وقابلة للتوسع ومتقدمة أكثر.",
    },
    price: 5000,
    currency: "MAD",
    popular: true,
    features: {
      en: [
        "Fully custom-coded website",
        "Unique premium design created for your brand",
        "Hosting + domain name included for 1 year",
        "Professional email included",
        "Ultra-fast performance",
        "Advanced mobile optimization",
        "More modern and immersive interface",
        "Advanced animations and micro-interactions",
        "Possibility to add 3D or interactive visuals",
        "Custom sections designed for conversion",
        "Stronger structure and cleaner architecture",
        "Better scalability for future growth",
        "Content management space if needed",
        "Dedicated admin interface if needed",
        "Product, service, or booking management",
        "Advanced SEO-ready structure",
        "Better image optimization and performance strategy",
        "Higher flexibility than template-based websites",
        "Stronger brand storytelling",
        "Premium user experience",
        "Personalized tutorial videos",
        "Priority guidance during the project",
        "Support after launch",
      ],
      fr: [
        "Site web entièrement codé sur-mesure",
        "Design premium unique créé pour votre marque",
        "Hébergement + nom de domaine inclus pendant 1 an",
        "Email professionnel inclus",
        "Performance ultra-rapide",
        "Optimisation mobile avancée",
        "Interface plus moderne et immersive",
        "Animations avancées et micro-interactions",
        "Possibilité d'ajouter des visuels 3D ou interactifs",
        "Sections sur-mesure conçues pour la conversion",
        "Structure plus solide et architecture plus propre",
        "Meilleure évolutivité pour la croissance future",
        "Espace de gestion de contenu si nécessaire",
        "Interface d'administration dédiée si nécessaire",
        "Gestion des produits, services ou réservations",
        "Structure avancée prête pour le référencement",
        "Meilleure optimisation des images et stratégie de performance",
        "Plus grande flexibilité qu'un site basé sur un modèle",
        "Storytelling de marque plus fort",
        "Expérience utilisateur premium",
        "Vidéos tutorielles personnalisées",
        "Accompagnement prioritaire pendant le projet",
        "Support après lancement",
      ],
      ar: [
        "موقع مبرمج بالكامل حسب الطلب",
        "تصميم Premium فريد مصمم خصيصًا لعلامتك التجارية",
        "استضافة + اسم نطاق لمدة سنة كاملة",
        "بريد إلكتروني احترافي مشمول",
        "أداء فائق السرعة",
        "تحسين متقدم للهاتف المحمول",
        "واجهة أكثر عصرية وغامرة",
        "رسوم متحركة متقدمة وتفاعلات دقيقة",
        "إمكانية إضافة عناصر 3D أو تفاعلية",
        "أقسام مخصصة مصممة لزيادة التحويل",
        "بنية أقوى وهيكلة أكثر وضوحًا",
        "قابلية توسع أفضل لنمو مستقبلي",
        "مساحة لإدارة المحتوى عند الحاجة",
        "واجهة إدارة مخصصة عند الحاجة",
        "إدارة المنتجات أو الخدمات أو الحجوزات",
        "بنية متقدمة جاهزة لتحسين محركات البحث",
        "تحسين أفضل للصور واستراتيجية أداء متقدمة",
        "مرونة أكبر مقارنة بالمواقع الجاهزة",
        "سرد أقوى لقصة العلامة التجارية",
        "تجربة استخدام Premium",
        "فيديوهات تعليمية مخصصة",
        "مرافقة ذات أولوية خلال المشروع",
        "دعم بعد الإطلاق",
      ],
    },
  },
];

export const pricingComparisonRows: PricingComparisonRow[] = [
  {
    feature: { en: "Technology", fr: "Technologie", ar: "التقنية" },
    wordpress: { en: "WordPress", fr: "WordPress", ar: "ووردبريس" },
    custom: {
      en: "Fully custom code",
      fr: "Code entièrement sur-mesure",
      ar: "كود مبرمج بالكامل حسب الطلب",
    },
  },
  {
    feature: { en: "Design", fr: "Design", ar: "التصميم" },
    wordpress: {
      en: "Modern, professional",
      fr: "Moderne, professionnel",
      ar: "عصري واحترافي",
    },
    custom: {
      en: "Fully unique, premium",
      fr: "Entièrement unique, premium",
      ar: "فريد بالكامل و premium",
    },
  },
  {
    feature: { en: "Best for", fr: "Idéal pour", ar: "الأنسب لـ" },
    wordpress: {
      en: "Fast launch, smaller budget",
      fr: "Lancement rapide, petit budget",
      ar: "إطلاق سريع وميزانية محدودة",
    },
    custom: {
      en: "Brands wanting a premium edge",
      fr: "Marques voulant se démarquer",
      ar: "علامات تجارية تريد تميزًا premium",
    },
  },
  {
    feature: { en: "Speed", fr: "Vitesse", ar: "السرعة" },
    wordpress: { en: "Good", fr: "Bonne", ar: "جيدة" },
    custom: {
      en: "Ultra-fast",
      fr: "Ultra-rapide",
      ar: "فائقة السرعة",
    },
  },
  {
    feature: { en: "Animations & 3D", fr: "Animations & 3D", ar: "الرسوم المتحركة و3D" },
    wordpress: { en: "Basic", fr: "Basiques", ar: "أساسية" },
    custom: {
      en: "Advanced, optional 3D",
      fr: "Avancées, 3D possible",
      ar: "متقدمة مع إمكانية 3D",
    },
  },
  {
    feature: { en: "Scalability", fr: "Évolutivité", ar: "قابلية التوسع" },
    wordpress: {
      en: "Good for most businesses",
      fr: "Adaptée à la plupart des entreprises",
      ar: "مناسبة لمعظم الشركات",
    },
    custom: {
      en: "Built for future growth",
      fr: "Conçue pour la croissance future",
      ar: "مصممة للنمو المستقبلي",
    },
  },
  {
    feature: { en: "Content management", fr: "Gestion de contenu", ar: "إدارة المحتوى" },
    wordpress: {
      en: "WordPress dashboard",
      fr: "Tableau de bord WordPress",
      ar: "لوحة تحكم ووردبريس",
    },
    custom: {
      en: "Dedicated admin space",
      fr: "Espace admin dédié",
      ar: "مساحة إدارة مخصصة",
    },
  },
  {
    feature: { en: "Hosting & domain (1 year)", fr: "Hébergement & domaine (1 an)", ar: "الاستضافة والنطاق (سنة)" },
    wordpress: { en: "Included", fr: "Inclus", ar: "مشمول" },
    custom: { en: "Included", fr: "Inclus", ar: "مشمول" },
  },
  {
    feature: { en: "Starting price", fr: "Prix de départ", ar: "السعر الابتدائي" },
    wordpress: { en: "2,500 MAD", fr: "2 500 MAD", ar: "2,500 درهم" },
    custom: { en: "5,000 MAD", fr: "5 000 MAD", ar: "5,000 درهم" },
  },
];
