import type { PricingComparisonRow, PricingPackage } from "@/types";

export const pricingPackages: PricingPackage[] = [
  {
    id: "essentiel",
    engine: "essentiel",
    name: {
      en: "Essentiel",
      fr: "Essentiel",
      ar: "Essentiel",
    },
    purpose: {
      en: "The ideal choice to launch your business online.",
      fr: "Le choix idéal pour lancer votre activité.",
      ar: "الخيار المثالي لإطلاق نشاطك التجاري عبر الإنترنت.",
    },
    description: {
      en: "A professional solution to launch your online presence with a modern, responsive, easy-to-manage website — ideal for presenting your services, products, or business with confidence.",
      fr: "Une solution professionnelle pour lancer votre présence en ligne avec un site moderne, responsive et facile à gérer, idéal pour présenter vos services, vos produits ou votre activité avec confiance.",
      ar: "حل احترافي لإطلاق حضورك الرقمي من خلال موقع عصري، متجاوب وسهل الإدارة، مناسب لعرض خدماتك أو منتجاتك أو نشاطك بطريقة موثوقة.",
    },
    price: 2500,
    currency: "MAD",
    popular: false,
    features: {
      en: [
        "Professional, modern website",
        "Responsive design for mobile, tablet, and desktop",
        "Domain name included for 1 year",
        "Hosting included for 1 year",
        "Professional email included",
        "Simple admin space to manage your content",
        "Easy management via WordPress",
        "Essential pages tailored to your business",
        "Showcase your services, products, or work",
        "Contact form or quote request",
        "Basic Google optimization",
        "Essential security",
        "WhatsApp integration available",
        "Tutorial videos after delivery",
        "Personalized guidance before launch",
      ],
      fr: [
        "Site web professionnel et moderne",
        "Design responsive pour mobile, tablette et ordinateur",
        "Domaine inclus pendant 1 an",
        "Hébergement inclus pendant 1 an",
        "Email professionnel inclus",
        "Espace d'administration simple pour gérer votre contenu",
        "Gestion facile via WordPress",
        "Pages essentielles selon votre activité",
        "Présentation de vos services, produits ou réalisations",
        "Formulaire de contact ou demande de devis",
        "Optimisation de base pour Google",
        "Sécurité essentielle",
        "Intégration WhatsApp possible",
        "Vidéos tutoriels après livraison",
        "Accompagnement personnalisé avant le lancement",
      ],
      ar: [
        "موقع إلكتروني احترافي وعصري",
        "تصميم متجاوب مع الهاتف، اللوحة الإلكترونية والحاسوب",
        "اسم نطاق مشمول لمدة سنة",
        "استضافة مشمولة لمدة سنة",
        "بريد إلكتروني احترافي",
        "مساحة إدارة سهلة لتعديل المحتوى",
        "إدارة مبسطة عبر WordPress",
        "صفحات أساسية حسب طبيعة النشاط",
        "عرض الخدمات، المنتجات أو الأعمال السابقة",
        "نموذج تواصل أو طلب عرض سعر",
        "تحسينات أساسية لمحركات البحث",
        "إعدادات أمان أساسية",
        "إمكانية إضافة زر واتساب",
        "فيديوهات شرح بعد التسليم",
        "مرافقة شخصية قبل إطلاق الموقع",
      ],
    },
  },
  {
    id: "premium-sur-mesure",
    engine: "premium",
    name: {
      en: "Premium Sur-Mesure",
      fr: "Premium Sur-Mesure",
      ar: "Premium Sur-Mesure",
    },
    purpose: {
      en: "Designed for businesses that want to stand out.",
      fr: "Conçu pour les entreprises qui veulent se démarquer.",
      ar: "مصممة للشركات التي ترغب في التميز عن منافسيها.",
    },
    description: {
      en: "For businesses that want to invest in a high-end website, designed to strengthen their brand image, deliver an exceptional user experience, and support their growth over the long term.",
      fr: "Pour les entreprises qui souhaitent investir dans un site web haut de gamme, conçu pour renforcer leur image de marque, offrir une expérience utilisateur exceptionnelle et accompagner leur croissance sur le long terme.",
      ar: "للشركات والمشاريع التي ترغب في الاستثمار في موقع إلكتروني عالي الجودة، مصمم لتعزيز صورتها الاحترافية، تقديم تجربة استخدام مميزة، ومواكبة نموها على المدى الطويل.",
    },
    valueStatement: {
      en: "An exclusive digital experience — faster, smoother, and built specifically around your business.",
      fr: "Une expérience digitale exclusive, plus rapide, plus fluide et conçue spécialement pour votre activité.",
      ar: "تجربة رقمية حصرية، أسرع وأكثر سلاسة، مصممة خصيصاً حسب طبيعة نشاطك وأهدافك.",
    },
    price: 5000,
    currency: "MAD",
    popular: true,
    features: {
      en: [
        "Custom website with a premium visual identity",
        "High-end user experience",
        "Faster, smoother, more immersive interface",
        "Unique design built around your brand",
        "Structure designed to build trust and convert more visitors",
        "Premium animations and modern micro-interactions",
        "Option to add interactive or 3D elements",
        "Exceptional performance and fast loading",
        "More flexible architecture to support growth",
        "Custom dashboard tailored to your project's needs",
        "Management of products, services, bookings, or requests",
        "Possible connection with external tools and APIs",
        "Possible connection with a delivery company system when available",
        "Email notifications for orders, forms, or important requests",
        "Payment methods based on your needs: cash on delivery, card payment, or payment gateway when available",
        "Enhanced security and technical best practices",
        "Advanced image and performance optimization",
        "More advanced SEO structure",
        "Domain name included for 1 year",
        "Hosting included for 1 year",
        "Professional email included",
        "Personalized advice to improve how your business is presented",
        "Personalized tutorial videos after delivery",
        "Priority support after launch",
      ],
      fr: [
        "Site web sur mesure avec une identité visuelle premium",
        "Expérience utilisateur haut de gamme",
        "Interface plus rapide, plus fluide et plus immersive",
        "Design unique conçu autour de votre marque",
        "Structure pensée pour inspirer confiance et convertir plus de visiteurs",
        "Animations premium et micro-interactions modernes",
        "Possibilité d'ajouter des éléments interactifs ou 3D",
        "Performance exceptionnelle et chargement rapide",
        "Architecture plus flexible pour accompagner la croissance",
        "Tableau de bord personnalisé selon les besoins du projet",
        "Gestion des produits, services, réservations ou demandes",
        "Connexion possible avec des outils externes et APIs",
        "Possibilité de connexion avec un système de livraison lorsque disponible",
        "Notifications email pour les commandes, formulaires ou demandes importantes",
        "Méthodes de paiement selon les besoins : paiement à la livraison, carte bancaire ou passerelle de paiement disponible",
        "Sécurité renforcée et bonnes pratiques techniques",
        "Optimisation avancée des images et de la performance",
        "Structure SEO plus avancée",
        "Domaine inclus pendant 1 an",
        "Hébergement inclus pendant 1 an",
        "Email professionnel inclus",
        "Conseils personnalisés pour améliorer la présentation de votre activité",
        "Vidéos tutoriels personnalisées après livraison",
        "Support prioritaire après le lancement",
      ],
      ar: [
        "موقع إلكتروني مصمم خصيصاً بهوية بصرية احترافية",
        "تجربة استخدام عالية الجودة",
        "واجهة أسرع، أكثر سلاسة وأكثر تفاعلاً",
        "تصميم فريد مبني حول هوية مشروعك",
        "بنية مصممة لتعزيز الثقة وتحويل الزوار إلى عملاء",
        "حركات بصرية احترافية وتفاعلات عصرية",
        "إمكانية إضافة عناصر تفاعلية أو ثلاثية الأبعاد",
        "أداء استثنائي وسرعة تحميل عالية",
        "بنية مرنة قابلة للتطوير مع نمو المشروع",
        "لوحة تحكم مخصصة حسب احتياجات المشروع",
        "إدارة المنتجات، الخدمات، الحجوزات أو الطلبات",
        "إمكانية الربط مع أدوات خارجية وواجهات API",
        "إمكانية الربط مع نظام شركة التوصيل عند توفره",
        "إشعارات عبر البريد الإلكتروني للطلبات والنماذج والعمليات المهمة",
        "طرق دفع حسب الحاجة: الدفع عند الاستلام، البطاقة البنكية أو بوابات الدفع المتاحة",
        "أمان معزز وممارسات تقنية احترافية",
        "تحسين متقدم للصور والأداء",
        "بنية محسنة أكثر لمحركات البحث",
        "اسم نطاق مشمول لمدة سنة",
        "استضافة مشمولة لمدة سنة",
        "بريد إلكتروني احترافي",
        "نصائح مخصصة لتحسين طريقة عرض نشاطك",
        "فيديوهات شرح مخصصة بعد التسليم",
        "دعم بأولوية بعد إطلاق الموقع",
      ],
    },
  },
];

export const pricingComparisonRows: PricingComparisonRow[] = [
  {
    feature: { en: "User experience", fr: "Expérience utilisateur", ar: "تجربة المستخدم" },
    essentiel: { en: "★★★★☆", fr: "★★★★☆", ar: "★★★★☆" },
    premium: { en: "★★★★★", fr: "★★★★★", ar: "★★★★★" },
  },
  {
    feature: { en: "Performance", fr: "Performance", ar: "الأداء" },
    essentiel: { en: "Excellent", fr: "Excellente", ar: "ممتاز" },
    premium: { en: "Exceptional", fr: "Exceptionnelle", ar: "استثنائي" },
  },
  {
    feature: { en: "Customization", fr: "Personnalisation", ar: "التخصيص" },
    essentiel: { en: "High", fr: "Élevée", ar: "مرتفع" },
    premium: { en: "Unlimited", fr: "Illimitée", ar: "غير محدود حسب المشروع" },
  },
  {
    feature: { en: "Animations", fr: "Animations", ar: "الحركات البصرية" },
    essentiel: { en: "Modern", fr: "Modernes", ar: "عصرية" },
    premium: {
      en: "Premium & immersive",
      fr: "Premium & immersives",
      ar: "احترافية وتفاعلية",
    },
  },
  {
    feature: { en: "Scalability", fr: "Évolutivité", ar: "قابلية التطوير" },
    essentiel: { en: "Very good", fr: "Très bonne", ar: "جيدة جداً" },
    premium: { en: "Maximum", fr: "Maximale", ar: "عالية جداً" },
  },
  {
    feature: { en: "Brand image", fr: "Image de marque", ar: "صورة العلامة التجارية" },
    essentiel: { en: "Professional", fr: "Professionnelle", ar: "احترافية" },
    premium: { en: "High-end", fr: "Haut de gamme", ar: "راقية ومميزة" },
  },
  {
    feature: { en: "Content management", fr: "Gestion du contenu", ar: "إدارة المحتوى" },
    essentiel: {
      en: "Simple and efficient",
      fr: "Simple et efficace",
      ar: "سهلة وفعالة",
    },
    premium: {
      en: "Tailored to the project",
      fr: "Personnalisée selon le projet",
      ar: "مخصصة حسب المشروع",
    },
  },
  {
    feature: { en: "Ideal for", fr: "Idéal pour", ar: "مناسب لـ" },
    essentiel: {
      en: "SMEs & independents",
      fr: "PME & indépendants",
      ar: "المشاريع الصغيرة والمستقلين",
    },
    premium: {
      en: "Growing brands & businesses",
      fr: "Marques & entreprises en croissance",
      ar: "العلامات والمشاريع في طور النمو",
    },
  },
];
